import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { i18n } from '@/config/i18n.config';

const inter = Inter({ subsets: ['latin'] })

const locales = ['en', 'pt'];
 
export function generateStaticParams() {
  const languages = i18n.locales.map((lang) => ({lang}));
  return languages;
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function LocaleLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: {lang: string};
}) {
  return (
    <html lang={params.lang} >
        <body className={inter.className}>{children}</body>
    </html>
  );
}
